#DEFINE x_CONNECTION "HBYSDataConnect"

* *********************************************************************
* *
* * 1/3/2001 FESYS.DBC 12:26:07
* *
* *********************************************************************
* *
* * Description:
* * This program was automatically generated by GenDBCX Version 1.1,
* * a modified version of Microsoft's utility GenDBC Version 2.26.67.
* *
* *********************************************************************
**************************************************
** View setup for RV_GROUPS
**************************************************

Create SQL VIEW "RV_GROUPS" REMOTE CONNECTION x_CONNECTION ;
AS SELECT * FROM appgroups ORDER BY appgroups.cname
=DBSetProp('RV_GROUPS', 'View', 'UpdateType', 1)
=DBSetProp('RV_GROUPS', 'View', 'WhereType', 3)
=DBSetProp('RV_GROUPS', 'View', 'FetchMemo', .T.)
=DBSetProp('RV_GROUPS', 'View', 'SendUpdates', .T.)
=DBSetProp('RV_GROUPS', 'View', 'UseMemoSize', 255)
=DBSetProp('RV_GROUPS', 'View', 'FetchSize', 100)
=DBSetProp('RV_GROUPS', 'View', 'MaxRecords', -1)
=DBSetProp('RV_GROUPS', 'View', 'Tables', 'appgroups')
=DBSetProp('RV_GROUPS', 'View', 'FetchSize', 100)
=DBSetProp('RV_GROUPS', 'View', 'Comment', "")
=DBSetProp('RV_GROUPS', 'View', 'BatchUpdateCount', 1)
=DBSetProp('RV_GROUPS', 'View', 'ShareConnection', .T.)
=DBSetProp('RV_GROUPS', 'View', 'Prepared', .F.)
=DBSetProp('RV_GROUPS', 'View', 'CompareMemo', .T.)
=DBSetProp('RV_GROUPS', 'View', 'FetchAsNeeded', .F.)

*!* Field Level Properties for RV_GROUPS

* Props for the RV_GROUPS.cgroup_id field.
=DBSetProp('RV_GROUPS.cgroup_id', 'Field', 'KeyField', .T.)
=DBSetProp('RV_GROUPS.cgroup_id', 'Field', 'Updatable', .T.)
=DBSetProp('RV_GROUPS.cgroup_id', 'Field', 'UpdateName', 'appgroups.cgroup_id')
=DBSetProp('RV_GROUPS.cgroup_id', 'Field', 'Caption', "Group Id")
=DBSetProp('RV_GROUPS.cgroup_id', 'Field', 'DataType', "C(16) NOCPTRANS")
=DBSetProp('RV_GROUPS.cgroup_id', 'Field', 'DefaultValue', "GUID()")

* Props for the RV_GROUPS.cname field.
=DBSetProp('RV_GROUPS.cname', 'Field', 'KeyField', .F.)
=DBSetProp('RV_GROUPS.cname', 'Field', 'Updatable', .T.)
=DBSetProp('RV_GROUPS.cname', 'Field', 'UpdateName', 'appgroups.cname')
=DBSetProp('RV_GROUPS.cname', 'Field', 'RuleExpression', "NOT EMPTY(cname)")
=DBSetProp('RV_GROUPS.cname', 'Field', 'RuleText', "'Group Name must be entered.'")
=DBSetProp('RV_GROUPS.cname', 'Field', 'Caption', "Group Name")
=DBSetProp('RV_GROUPS.cname', 'Field', 'DataType', "C(40)")

* Props for the RV_GROUPS.mdescript field.
=DBSetProp('RV_GROUPS.mdescript', 'Field', 'KeyField', .F.)
=DBSetProp('RV_GROUPS.mdescript', 'Field', 'Updatable', .T.)
=DBSetProp('RV_GROUPS.mdescript', 'Field', 'UpdateName', 'appgroups.mdescript')
=DBSetProp('RV_GROUPS.mdescript', 'Field', 'RuleExpression', "NOT EMPTY( mdescript)")
=DBSetProp('RV_GROUPS.mdescript', 'Field', 'RuleText', "'Description must be entered.'")
=DBSetProp('RV_GROUPS.mdescript', 'Field', 'Caption', "Description")
=DBSetProp('RV_GROUPS.mdescript', 'Field', 'DataType', "M")
 

**************************************************
** View setup for RV_CURRENTUSER
**************************************************
Local vp_cUserId
vp_cUserId = "A"

Create SQL VIEW "RV_CURRENTUSER" REMOTE CONNECTION x_CONNECTION ;
AS SELECT * FROM appusers WHERE appusers.cuserid = ?vp_cUserId

=DBSetProp('RV_CURRENTUSER', 'View', 'UpdateType', 1)
=DBSetProp('RV_CURRENTUSER', 'View', 'WhereType', 3)
=DBSetProp('RV_CURRENTUSER', 'View', 'FetchMemo', .T.)
=DBSetProp('RV_CURRENTUSER', 'View', 'SendUpdates', .T.)
=DBSetProp('RV_CURRENTUSER', 'View', 'UseMemoSize', 255)
=DBSetProp('RV_CURRENTUSER', 'View', 'FetchSize', 100)
=DBSetProp('RV_CURRENTUSER', 'View', 'MaxRecords', -1)
=DBSetProp('RV_CURRENTUSER', 'View', 'Tables', 'appusers')
=DBSetProp('RV_CURRENTUSER', 'View', 'FetchSize', 100)
=DBSetProp('RV_CURRENTUSER', 'View', 'ParameterList', "vp_cUserId,'C'")
=DBSetProp('RV_CURRENTUSER', 'View', 'Comment', "")
=DBSetProp('RV_CURRENTUSER', 'View', 'BatchUpdateCount', 1)
=DBSetProp('RV_CURRENTUSER', 'View', 'ShareConnection', .T.)
=DBSetProp('RV_CURRENTUSER', 'View', 'Prepared', .F.)
=DBSetProp('RV_CURRENTUSER', 'View', 'CompareMemo', .T.)
=DBSetProp('RV_CURRENTUSER', 'View', 'FetchAsNeeded', .F.)

*!* Field Level Properties for RV_CURRENTUSER

* Props for the RV_CURRENTUSER.cuserid field.
=DBSetProp('RV_CURRENTUSER.cuserid', 'Field', 'KeyField', .T.)
=DBSetProp('RV_CURRENTUSER.cuserid', 'Field', 'Updatable', .T.)
=DBSetProp('RV_CURRENTUSER.cuserid', 'Field', 'UpdateName', 'appusers.cuserid')
=DBSetProp('RV_CURRENTUSER.cuserid', 'Field', 'DataType', "C(30)")

* Props for the RV_CURRENTUSER.cfirst_name field.
=DBSetProp('RV_CURRENTUSER.cfirst_name', 'Field', 'KeyField', .F.)
=DBSetProp('RV_CURRENTUSER.cfirst_name', 'Field', 'Updatable', .T.)
=DBSetProp('RV_CURRENTUSER.cfirst_name', 'Field', 'UpdateName', 'appusers.cfirst_name')
=DBSetProp('RV_CURRENTUSER.cfirst_name', 'Field', 'DataType', "C(20)")

* Props for the RV_CURRENTUSER.clast_name field.
=DBSetProp('RV_CURRENTUSER.clast_name', 'Field', 'KeyField', .F.)
=DBSetProp('RV_CURRENTUSER.clast_name', 'Field', 'Updatable', .T.)
=DBSetProp('RV_CURRENTUSER.clast_name', 'Field', 'UpdateName', 'appusers.clast_name')
=DBSetProp('RV_CURRENTUSER.clast_name', 'Field', 'DataType', "C(25)")

* Props for the RV_CURRENTUSER.cpassword field.
=DBSetProp('RV_CURRENTUSER.cpassword', 'Field', 'KeyField', .F.)
=DBSetProp('RV_CURRENTUSER.cpassword', 'Field', 'Updatable', .T.)
=DBSetProp('RV_CURRENTUSER.cpassword', 'Field', 'UpdateName', 'appusers.cpassword')
=DBSetProp('RV_CURRENTUSER.cpassword', 'Field', 'DataType', "C(30)")

* Props for the RV_CURRENTUSER.dlastchanged field.
=DBSetProp('RV_CURRENTUSER.dlastchanged', 'Field', 'KeyField', .F.)
=DBSetProp('RV_CURRENTUSER.dlastchanged', 'Field', 'Updatable', .T.)
=DBSetProp('RV_CURRENTUSER.dlastchanged', 'Field', 'UpdateName', 'appusers.dlastchanged')
=DBSetProp('RV_CURRENTUSER.dlastchanged', 'Field', 'DataType', "D")

* Props for the RV_CURRENTUSER.ladministrator field.
=DBSetProp('RV_CURRENTUSER.ladministrator', 'Field', 'KeyField', .F.)
=DBSetProp('RV_CURRENTUSER.ladministrator', 'Field', 'Updatable', .T.)
=DBSetProp('RV_CURRENTUSER.ladministrator', 'Field', 'UpdateName', 'appusers.ladministrator')
=DBSetProp('RV_CURRENTUSER.ladministrator', 'Field', 'DataType', "L")

* Props for the RV_CURRENTUSER.cgroup_id field.

=DBSetProp('RV_CURRENTUSER.cgroup_id', 'Field', 'KeyField', .F.)
=DBSetProp('RV_CURRENTUSER.cgroup_id', 'Field', 'Updatable', .T.)
=DBSetProp('RV_CURRENTUSER.cgroup_id', 'Field', 'UpdateName', 'appusers.cgroup_id')
=DBSetProp('RV_CURRENTUSER.cgroup_id', 'Field', 'DataType', "C(16) NOCPTRANS")

* Props for the RV_CURRENTUSER.moldpasswords field.
=DBSetProp('RV_CURRENTUSER.moldpasswords', 'Field', 'KeyField', .F.)
=DBSetProp('RV_CURRENTUSER.moldpasswords', 'Field', 'Updatable', .T.)
=DBSetProp('RV_CURRENTUSER.moldpasswords', 'Field', 'UpdateName', 'appusers.moldpasswords')
=DBSetProp('RV_CURRENTUSER.moldpasswords', 'Field', 'DataType', "M")

* Props for the RV_CURRENTUSER.linactive field.
=DBSetProp('RV_CURRENTUSER.linactive', 'Field', 'KeyField', .F.)
=DBSetProp('RV_CURRENTUSER.linactive', 'Field', 'Updatable', .T.)
=DBSetProp('RV_CURRENTUSER.linactive', 'Field', 'UpdateName', 'appusers.linactive')
=DBSetProp('RV_CURRENTUSER.linactive', 'Field', 'DataType', "L")
 

**************************************************
** View setup for RV_LOGIN
**************************************************

Create SQL VIEW "RV_LOGIN" REMOTE CONNECTION x_CONNECTION ;
AS SELECT * FROM appusers ORDER BY appusers.cuserid

=DBSetProp('RV_LOGIN', 'View', 'UpdateType', 1)
=DBSetProp('RV_LOGIN', 'View', 'WhereType', 3)
=DBSetProp('RV_LOGIN', 'View', 'FetchMemo', .T.)
=DBSetProp('RV_LOGIN', 'View', 'SendUpdates', .T.)
=DBSetProp('RV_LOGIN', 'View', 'UseMemoSize', 255)
=DBSetProp('RV_LOGIN', 'View', 'FetchSize', 100)
=DBSetProp('RV_LOGIN', 'View', 'MaxRecords', -1)
=DBSetProp('RV_LOGIN', 'View', 'Tables', 'appusers')
=DBSetProp('RV_LOGIN', 'View', 'FetchSize', 100)
=DBSetProp('RV_LOGIN', 'View', 'Comment', "")
=DBSetProp('RV_LOGIN', 'View', 'BatchUpdateCount', 1)
=DBSetProp('RV_LOGIN', 'View', 'ShareConnection', .T.)
=DBSetProp('RV_LOGIN', 'View', 'Prepared', .F.)
=DBSetProp('RV_LOGIN', 'View', 'CompareMemo', .T.)
=DBSetProp('RV_LOGIN', 'View', 'FetchAsNeeded', .F.)

*!* Field Level Properties for RV_LOGIN

* Props for the RV_LOGIN.cuserid field.
=DBSetProp('RV_LOGIN.cuserid', 'Field', 'KeyField', .T.)
=DBSetProp('RV_LOGIN.cuserid', 'Field', 'Updatable', .T.)
=DBSetProp('RV_LOGIN.cuserid', 'Field', 'UpdateName', 'appusers.cuserid')
=DBSetProp('RV_LOGIN.cuserid', 'Field', 'DataType', "C(30)")

* Props for the RV_LOGIN.cfirst_name field.
=DBSetProp('RV_LOGIN.cfirst_name', 'Field', 'KeyField', .F.)
=DBSetProp('RV_LOGIN.cfirst_name', 'Field', 'Updatable', .T.)
=DBSetProp('RV_LOGIN.cfirst_name', 'Field', 'UpdateName', 'appusers.cfirst_name')
=DBSetProp('RV_LOGIN.cfirst_name', 'Field', 'DataType', "C(20)")

* Props for the RV_LOGIN.clast_name field.
=DBSetProp('RV_LOGIN.clast_name', 'Field', 'KeyField', .F.)
=DBSetProp('RV_LOGIN.clast_name', 'Field', 'Updatable', .T.)
=DBSetProp('RV_LOGIN.clast_name', 'Field', 'UpdateName', 'appusers.clast_name')
=DBSetProp('RV_LOGIN.clast_name', 'Field', 'DataType', "C(25)")

* Props for the RV_LOGIN.cpassword field.
=DBSetProp('RV_LOGIN.cpassword', 'Field', 'KeyField', .F.)
=DBSetProp('RV_LOGIN.cpassword', 'Field', 'Updatable', .T.)
=DBSetProp('RV_LOGIN.cpassword', 'Field', 'UpdateName', 'appusers.cpassword')
=DBSetProp('RV_LOGIN.cpassword', 'Field', 'DataType', "C(30)")

* Props for the RV_LOGIN.dlastchanged field.
=DBSetProp('RV_LOGIN.dlastchanged', 'Field', 'KeyField', .F.)
=DBSetProp('RV_LOGIN.dlastchanged', 'Field', 'Updatable', .T.)
=DBSetProp('RV_LOGIN.dlastchanged', 'Field', 'UpdateName', 'appusers.dlastchanged')
=DBSetProp('RV_LOGIN.dlastchanged', 'Field', 'DataType', "D")

* Props for the RV_LOGIN.ladministrator field.
=DBSetProp('RV_LOGIN.ladministrator', 'Field', 'KeyField', .F.)
=DBSetProp('RV_LOGIN.ladministrator', 'Field', 'Updatable', .T.)
=DBSetProp('RV_LOGIN.ladministrator', 'Field', 'UpdateName', 'appusers.ladministrator')
=DBSetProp('RV_LOGIN.ladministrator', 'Field', 'DataType', "L")

* Props for the RV_LOGIN.cgroup_id field.
=DBSetProp('RV_LOGIN.cgroup_id', 'Field', 'KeyField', .F.)
=DBSetProp('RV_LOGIN.cgroup_id', 'Field', 'Updatable', .T.)
=DBSetProp('RV_LOGIN.cgroup_id', 'Field', 'UpdateName', 'appusers.cgroup_id')
=DBSetProp('RV_LOGIN.cgroup_id', 'Field', 'DataType', "C(16) NOCPTRANS")

* Props for the RV_LOGIN.moldpasswords field.
=DBSetProp('RV_LOGIN.moldpasswords', 'Field', 'KeyField', .F.)
=DBSetProp('RV_LOGIN.moldpasswords', 'Field', 'Updatable', .T.)
=DBSetProp('RV_LOGIN.moldpasswords', 'Field', 'UpdateName', 'appusers.moldpasswords')
=DBSetProp('RV_LOGIN.moldpasswords', 'Field', 'DataType', "M")

* Props for the RV_LOGIN.linactive field.
=DBSetProp('RV_LOGIN.linactive', 'Field', 'KeyField', .F.)
=DBSetProp('RV_LOGIN.linactive', 'Field', 'Updatable', .T.)
=DBSetProp('RV_LOGIN.linactive', 'Field', 'UpdateName', 'appusers.linactive')
=DBSetProp('RV_LOGIN.linactive', 'Field', 'DataType', "L")

**************************************************
** View setup for RV_LOGINS
**************************************************

Create SQL VIEW "RV_LOGINS" REMOTE CONNECTION x_CONNECTION ;
AS SELECT * FROM applogin

=DBSetProp('RV_LOGINS', 'View', 'UpdateType', 1)
=DBSetProp('RV_LOGINS', 'View', 'WhereType', 3)
=DBSetProp('RV_LOGINS', 'View', 'FetchMemo', .T.)
=DBSetProp('RV_LOGINS', 'View', 'SendUpdates', .T.)
=DBSetProp('RV_LOGINS', 'View', 'UseMemoSize', 255)
=DBSetProp('RV_LOGINS', 'View', 'FetchSize', 100)
=DBSetProp('RV_LOGINS', 'View', 'MaxRecords', -1)
=DBSetProp('RV_LOGINS', 'View', 'Tables', 'applogin')
=DBSetProp('RV_LOGINS', 'View', 'FetchSize', 100)
=DBSetProp('RV_LOGINS', 'View', 'Comment', "")
=DBSetProp('RV_LOGINS', 'View', 'BatchUpdateCount', 1)
=DBSetProp('RV_LOGINS', 'View', 'ShareConnection', .T.)
=DBSetProp('RV_LOGINS', 'View', 'Prepared', .F.)
=DBSetProp('RV_LOGINS', 'View', 'CompareMemo', .T.)
=DBSetProp('RV_LOGINS', 'View', 'FetchAsNeeded', .F.)

*!* Field Level Properties for RV_LOGINS

* Props for the RV_LOGINS.cuserid field.
=DBSetProp('RV_LOGINS.cuserid', 'Field', 'KeyField', .T.)
=DBSetProp('RV_LOGINS.cuserid', 'Field', 'Updatable', .T.)
=DBSetProp('RV_LOGINS.cuserid', 'Field', 'UpdateName', 'applogin.cuserid')
=DBSetProp('RV_LOGINS.cuserid', 'Field', 'DataType', "C(30)")

* Props for the RV_LOGINS.tloggedin field.
=DBSetProp('RV_LOGINS.tloggedin', 'Field', 'KeyField', .T.)
=DBSetProp('RV_LOGINS.tloggedin', 'Field', 'Updatable', .T.)
=DBSetProp('RV_LOGINS.tloggedin', 'Field', 'UpdateName', 'applogin.tloggedin')
=DBSetProp('RV_LOGINS.tloggedin', 'Field', 'DataType', "T")
=DBSetProp('RV_LOGINS.tloggedin', 'Field', 'DefaultValue', "DATETIME()")

* Props for the RV_LOGINS.tloggedout field.
=DBSetProp('RV_LOGINS.tloggedout', 'Field', 'KeyField', .F.)
=DBSetProp('RV_LOGINS.tloggedout', 'Field', 'Updatable', .T.)
=DBSetProp('RV_LOGINS.tloggedout', 'Field', 'UpdateName', 'applogin.tloggedout')
=DBSetProp('RV_LOGINS.tloggedout', 'Field', 'DataType', "T")

* Props for the RV_LOGINS.tcleared field.
=DBSetProp('RV_LOGINS.tcleared', 'Field', 'KeyField', .F.)
=DBSetProp('RV_LOGINS.tcleared', 'Field', 'Updatable', .T.)
=DBSetProp('RV_LOGINS.tcleared', 'Field', 'UpdateName', 'applogin.tcleared')
=DBSetProp('RV_LOGINS.tcleared', 'Field', 'DataType', "T")

* Props for the RV_LOGINS.cclearedby field.
=DBSetProp('RV_LOGINS.cclearedby', 'Field', 'KeyField', .F.)
=DBSetProp('RV_LOGINS.cclearedby', 'Field', 'Updatable', .T.)
=DBSetProp('RV_LOGINS.cclearedby', 'Field', 'UpdateName', 'applogin.cclearedby')
=DBSetProp('RV_LOGINS.cclearedby', 'Field', 'DataType', "C(30)")
 

**************************************************
** View setup for RV_APPINFO
**************************************************

Create SQL VIEW "RV_APPINFO" REMOTE CONNECTION x_CONNECTION ;
AS SELECT * FROM appinfo

=DBSetProp('RV_APPINFO', 'View', 'UpdateType', 1)
=DBSetProp('RV_APPINFO', 'View', 'WhereType', 3)
=DBSetProp('RV_APPINFO', 'View', 'FetchMemo', .T.)
=DBSetProp('RV_APPINFO', 'View', 'SendUpdates', .T.)
=DBSetProp('RV_APPINFO', 'View', 'UseMemoSize', 255)
=DBSetProp('RV_APPINFO', 'View', 'FetchSize', 100)
=DBSetProp('RV_APPINFO', 'View', 'MaxRecords', -1)
=DBSetProp('RV_APPINFO', 'View', 'Tables', 'appinfo')
=DBSetProp('RV_APPINFO', 'View', 'FetchSize', 100)
=DBSetProp('RV_APPINFO', 'View', 'Comment', "")
=DBSetProp('RV_APPINFO', 'View', 'BatchUpdateCount', 1)
=DBSetProp('RV_APPINFO', 'View', 'ShareConnection', .T.)
=DBSetProp('RV_APPINFO', 'View', 'Prepared', .F.)
=DBSetProp('RV_APPINFO', 'View', 'CompareMemo', .T.)
=DBSetProp('RV_APPINFO', 'View', 'FetchAsNeeded', .F.)

*!* Field Level Properties for RV_APPINFO

* Props for the RV_APPINFO.cid field.
=DBSetProp('RV_APPINFO.cid', 'Field', 'KeyField', .T.)
=DBSetProp('RV_APPINFO.cid', 'Field', 'Updatable', .T.)
=DBSetProp('RV_APPINFO.cid', 'Field', 'UpdateName', 'appinfo.cid')
=DBSetProp('RV_APPINFO.cid', 'Field', 'DataType', "C(16) NOCPTRANS")
=DBSetProp('RV_APPINFO.cid', 'Field', 'DefaultValue', "GUID()")
=DBSetProp('RV_APPINFO.cid', 'Field', 'DisplayClass', "cactivedoc")
=DBSetProp('RV_APPINFO.cid', 'Field', 'DisplayClassLibrary', "c:\vfe6\vfeframe\libs\ccontrls.vcx")

* Props for the RV_APPINFO.nminpasswordlength field.
=DBSetProp('RV_APPINFO.nminpasswordlength', 'Field', 'KeyField', .F.)
=DBSetProp('RV_APPINFO.nminpasswordlength', 'Field', 'Updatable', .T.)
=DBSetProp('RV_APPINFO.nminpasswordlength', 'Field', 'UpdateName', 'appinfo.nminpasswordlength')
=DBSetProp('RV_APPINFO.nminpasswordlength', 'Field', 'DataType', "N(2)")
=DBSetProp('RV_APPINFO.nminpasswordlength', 'Field', 'DefaultValue', "4")
=DBSetProp('RV_APPINFO.nminpasswordlength', 'Field', 'DisplayClass', "cspinner")
=DBSetProp('RV_APPINFO.nminpasswordlength', 'Field', 'DisplayClassLibrary', "c:\vfe6\vfeframe\libs\ccontrls.vcx")

* Props for the RV_APPINFO.nminuseridlength field.

=DBSetProp('RV_APPINFO.nminuseridlength', 'Field', 'KeyField', .F.)
=DBSetProp('RV_APPINFO.nminuseridlength', 'Field', 'Updatable', .T.)
=DBSetProp('RV_APPINFO.nminuseridlength', 'Field', 'UpdateName', 'appinfo.nminuseridlength')
=DBSetProp('RV_APPINFO.nminuseridlength', 'Field', 'DataType', "N(2)")
=DBSetProp('RV_APPINFO.nminuseridlength', 'Field', 'DefaultValue', "3")
=DBSetProp('RV_APPINFO.nminuseridlength', 'Field', 'DisplayClass', "cspinner")
=DBSetProp('RV_APPINFO.nminuseridlength', 'Field', 'DisplayClassLibrary', "c:\vfe6\vfeframe\libs\ccontrls.vcx")

* Props for the RV_APPINFO.nmaxlogins field.
=DBSetProp('RV_APPINFO.nmaxlogins', 'Field', 'KeyField', .F.)
=DBSetProp('RV_APPINFO.nmaxlogins', 'Field', 'Updatable', .T.)
=DBSetProp('RV_APPINFO.nmaxlogins', 'Field', 'UpdateName', 'appinfo.nmaxlogins')
=DBSetProp('RV_APPINFO.nmaxlogins', 'Field', 'DataType', "N(2)")
=DBSetProp('RV_APPINFO.nmaxlogins', 'Field', 'DefaultValue', "1")
=DBSetProp('RV_APPINFO.nmaxlogins', 'Field', 'DisplayClass', "cspinner")
=DBSetProp('RV_APPINFO.nmaxlogins', 'Field', 'DisplayClassLibrary', "c:\vfe6\vfeframe\libs\ccontrls.vcx")

* Props for the RV_APPINFO.nfailures field.
=DBSetProp('RV_APPINFO.nfailures', 'Field', 'KeyField', .F.)
=DBSetProp('RV_APPINFO.nfailures', 'Field', 'Updatable', .T.)
=DBSetProp('RV_APPINFO.nfailures', 'Field', 'UpdateName', 'appinfo.nfailures')
=DBSetProp('RV_APPINFO.nfailures', 'Field', 'DataType', "N(2)")
=DBSetProp('RV_APPINFO.nfailures', 'Field', 'DefaultValue', "3")
=DBSetProp('RV_APPINFO.nfailures', 'Field', 'DisplayClass', "cspinner")
=DBSetProp('RV_APPINFO.nfailures', 'Field', 'DisplayClassLibrary', "c:\vfe6\vfeframe\libs\ccontrls.vcx")

* Props for the RV_APPINFO.luniquepassword field.
=DBSetProp('RV_APPINFO.luniquepassword', 'Field', 'KeyField', .F.)
=DBSetProp('RV_APPINFO.luniquepassword', 'Field', 'Updatable', .T.)
=DBSetProp('RV_APPINFO.luniquepassword', 'Field', 'UpdateName', 'appinfo.luniquepassword')
=DBSetProp('RV_APPINFO.luniquepassword', 'Field', 'DataType', "L")
=DBSetProp('RV_APPINFO.luniquepassword', 'Field', 'DefaultValue', ".T.")
=DBSetProp('RV_APPINFO.luniquepassword', 'Field', 'DisplayClass', "ccheckbox")
=DBSetProp('RV_APPINFO.luniquepassword', 'Field', 'DisplayClassLibrary', "c:\vfe6\vfeframe\libs\ccontrls.vcx")

* Props for the RV_APPINFO.nchangepassword field.
=DBSetProp('RV_APPINFO.nchangepassword', 'Field', 'KeyField', .F.)
=DBSetProp('RV_APPINFO.nchangepassword', 'Field', 'Updatable', .T.)
=DBSetProp('RV_APPINFO.nchangepassword', 'Field', 'UpdateName', 'appinfo.nchangepassword')
=DBSetProp('RV_APPINFO.nchangepassword', 'Field', 'DataType', "N(4)")
=DBSetProp('RV_APPINFO.nchangepassword', 'Field', 'DefaultValue', "0")
=DBSetProp('RV_APPINFO.nchangepassword', 'Field', 'DisplayClass', "cspinner")
=DBSetProp('RV_APPINFO.nchangepassword', 'Field', 'DisplayClassLibrary', "c:\vfe6\vfeframe\libs\ccontrls.vcx")

* Props for the RV_APPINFO.ndefaultlevel field.
=DBSetProp('RV_APPINFO.ndefaultlevel', 'Field', 'KeyField', .F.)
=DBSetProp('RV_APPINFO.ndefaultlevel', 'Field', 'Updatable', .T.)
=DBSetProp('RV_APPINFO.ndefaultlevel', 'Field', 'UpdateName', 'appinfo.ndefaultlevel')
=DBSetProp('RV_APPINFO.ndefaultlevel', 'Field', 'DataType', "N(1)")
=DBSetProp('RV_APPINFO.ndefaultlevel', 'Field', 'DefaultValue', "1")
=DBSetProp('RV_APPINFO.ndefaultlevel', 'Field', 'DisplayClass', "coptiongroup")
=DBSetProp('RV_APPINFO.ndefaultlevel', 'Field', 'DisplayClassLibrary', "c:\vfe6\vfeframe\libs\ccontrls.vcx")
 

**************************************************
** View setup for RV_SECURITYNAMES
**************************************************

Create SQL VIEW "RV_SECURITYNAMES" REMOTE CONNECTION x_CONNECTION ;
AS SELECT * FROM appnames

=DBSetProp('RV_SECURITYNAMES', 'View', 'UpdateType', 1)
=DBSetProp('RV_SECURITYNAMES', 'View', 'WhereType', 3)
=DBSetProp('RV_SECURITYNAMES', 'View', 'FetchMemo', .T.)
=DBSetProp('RV_SECURITYNAMES', 'View', 'SendUpdates', .T.)
=DBSetProp('RV_SECURITYNAMES', 'View', 'UseMemoSize', 255)
=DBSetProp('RV_SECURITYNAMES', 'View', 'FetchSize', 100)
=DBSetProp('RV_SECURITYNAMES', 'View', 'MaxRecords', -1)
=DBSetProp('RV_SECURITYNAMES', 'View', 'Tables', 'appnames')
=DBSetProp('RV_SECURITYNAMES', 'View', 'FetchSize', 100)
=DBSetProp('RV_SECURITYNAMES', 'View', 'Comment', "")
=DBSetProp('RV_SECURITYNAMES', 'View', 'BatchUpdateCount', 1)
=DBSetProp('RV_SECURITYNAMES', 'View', 'ShareConnection', .T.)
=DBSetProp('RV_SECURITYNAMES', 'View', 'Prepared', .F.)
=DBSetProp('RV_SECURITYNAMES', 'View', 'CompareMemo', .T.)
=DBSetProp('RV_SECURITYNAMES', 'View', 'FetchAsNeeded', .F.)

*!* Field Level Properties for RV_SECURITYNAMES

* Props for the RV_SECURITYNAMES.cname field.
=DBSetProp('RV_SECURITYNAMES.cname', 'Field', 'KeyField', .T.)
=DBSetProp('RV_SECURITYNAMES.cname', 'Field', 'Updatable', .T.)
=DBSetProp('RV_SECURITYNAMES.cname', 'Field', 'UpdateName', 'appnames.cname')
=DBSetProp('RV_SECURITYNAMES.cname', 'Field', 'DataType', "C(40)")

* Props for the RV_SECURITYNAMES.mdescription field.
=DBSetProp('RV_SECURITYNAMES.mdescription', 'Field', 'KeyField', .F.)
=DBSetProp('RV_SECURITYNAMES.mdescription', 'Field', 'Updatable', .T.)
=DBSetProp('RV_SECURITYNAMES.mdescription', 'Field', 'UpdateName', 'appnames.mdescription')
=DBSetProp('RV_SECURITYNAMES.mdescription', 'Field', 'DataType', "M")
 

**************************************************
** View setup for RV_RIGHTS
**************************************************

Create SQL VIEW "RV_RIGHTS" REMOTE CONNECTION x_CONNECTION ;
AS SELECT * FROM apprites WHERE apprites.cgroup_id = ?v_groups.cGroup_Id

=DBSetProp('RV_RIGHTS', 'View', 'UpdateType', 1)
=DBSetProp('RV_RIGHTS', 'View', 'WhereType', 3)
=DBSetProp('RV_RIGHTS', 'View', 'FetchMemo', .T.)
=DBSetProp('RV_RIGHTS', 'View', 'SendUpdates', .T.)
=DBSetProp('RV_RIGHTS', 'View', 'UseMemoSize', 255)
=DBSetProp('RV_RIGHTS', 'View', 'FetchSize', 100)
=DBSetProp('RV_RIGHTS', 'View', 'MaxRecords', -1)
=DBSetProp('RV_RIGHTS', 'View', 'Tables', 'apprites')
=DBSetProp('RV_RIGHTS', 'View', 'FetchSize', 100)
=DBSetProp('RV_RIGHTS', 'View', 'Comment', "")
=DBSetProp('RV_RIGHTS', 'View', 'BatchUpdateCount', 1)
=DBSetProp('RV_RIGHTS', 'View', 'ShareConnection', .T.)
=DBSetProp('RV_RIGHTS', 'View', 'Prepared', .F.)
=DBSetProp('RV_RIGHTS', 'View', 'CompareMemo', .T.)
=DBSetProp('RV_RIGHTS', 'View', 'FetchAsNeeded', .F.)

*!* Field Level Properties for RV_RIGHTS

* Props for the RV_RIGHTS.cgroup_id field.
=DBSetProp('RV_RIGHTS.cgroup_id', 'Field', 'KeyField', .T.)
=DBSetProp('RV_RIGHTS.cgroup_id', 'Field', 'Updatable', .T.)
=DBSetProp('RV_RIGHTS.cgroup_id', 'Field', 'UpdateName', 'apprites.cgroup_id')
=DBSetProp('RV_RIGHTS.cgroup_id', 'Field', 'DataType', "C(16) NOCPTRANS")

* Props for the RV_RIGHTS.cname field.
=DBSetProp('RV_RIGHTS.cname', 'Field', 'KeyField', .T.)
=DBSetProp('RV_RIGHTS.cname', 'Field', 'Updatable', .T.)
=DBSetProp('RV_RIGHTS.cname', 'Field', 'UpdateName', 'apprites.cname')
=DBSetProp('RV_RIGHTS.cname', 'Field', 'DataType', "C(40)")

* Props for the RV_RIGHTS.nrights field.
=DBSetProp('RV_RIGHTS.nrights', 'Field', 'KeyField', .F.)
=DBSetProp('RV_RIGHTS.nrights', 'Field', 'Updatable', .T.)
=DBSetProp('RV_RIGHTS.nrights', 'Field', 'UpdateName', 'apprites.nrights')
=DBSetProp('RV_RIGHTS.nrights', 'Field', 'DataType', "N(1)")

 
**************************************************
** View setup for RV_USERS
**************************************************

Create SQL VIEW "RV_USERS" REMOTE CONNECTION x_CONNECTION ;
AS SELECT * FROM appusers

=DBSetProp('RV_USERS', 'View', 'UpdateType', 1)
=DBSetProp('RV_USERS', 'View', 'WhereType', 3)
=DBSetProp('RV_USERS', 'View', 'FetchMemo', .T.)
=DBSetProp('RV_USERS', 'View', 'SendUpdates', .T.)
=DBSetProp('RV_USERS', 'View', 'UseMemoSize', 255)
=DBSetProp('RV_USERS', 'View', 'FetchSize', 100)
=DBSetProp('RV_USERS', 'View', 'MaxRecords', -1)
=DBSetProp('RV_USERS', 'View', 'Tables', 'appusers')
=DBSetProp('RV_USERS', 'View', 'FetchSize', 100)
=DBSetProp('RV_USERS', 'View', 'Comment', "")
=DBSetProp('RV_USERS', 'View', 'BatchUpdateCount', 1)
=DBSetProp('RV_USERS', 'View', 'ShareConnection', .T.)
=DBSetProp('RV_USERS', 'View', 'Prepared', .F.)
=DBSetProp('RV_USERS', 'View', 'CompareMemo', .T.)
=DBSetProp('RV_USERS', 'View', 'FetchAsNeeded', .F.)

*!* Field Level Properties for RV_USERS

* Props for the RV_USERS.cuserid field.
=DBSetProp('RV_USERS.cuserid', 'Field', 'KeyField', .T.)
=DBSetProp('RV_USERS.cuserid', 'Field', 'Updatable', .T.)
=DBSetProp('RV_USERS.cuserid', 'Field', 'UpdateName', 'appusers.cuserid')
=DBSetProp('RV_USERS.cuserid', 'Field', 'DataType', "C(30)")

* Props for the RV_USERS.cfirst_name field.
=DBSetProp('RV_USERS.cfirst_name', 'Field', 'KeyField', .F.)
=DBSetProp('RV_USERS.cfirst_name', 'Field', 'Updatable', .T.)
=DBSetProp('RV_USERS.cfirst_name', 'Field', 'UpdateName', 'appusers.cfirst_name')
=DBSetProp('RV_USERS.cfirst_name', 'Field', 'DataType', "C(20)")

* Props for the RV_USERS.clast_name field.
=DBSetProp('RV_USERS.clast_name', 'Field', 'KeyField', .F.)
=DBSetProp('RV_USERS.clast_name', 'Field', 'Updatable', .T.)
=DBSetProp('RV_USERS.clast_name', 'Field', 'UpdateName', 'appusers.clast_name')
=DBSetProp('RV_USERS.clast_name', 'Field', 'DataType', "C(25)")

* Props for the RV_USERS.cpassword field.
=DBSetProp('RV_USERS.cpassword', 'Field', 'KeyField', .F.)
=DBSetProp('RV_USERS.cpassword', 'Field', 'Updatable', .T.)
=DBSetProp('RV_USERS.cpassword', 'Field', 'UpdateName', 'appusers.cpassword')
=DBSetProp('RV_USERS.cpassword', 'Field', 'DataType', "C(30)")

* Props for the RV_USERS.dlastchanged field.
=DBSetProp('RV_USERS.dlastchanged', 'Field', 'KeyField', .F.)
=DBSetProp('RV_USERS.dlastchanged', 'Field', 'Updatable', .T.)
=DBSetProp('RV_USERS.dlastchanged', 'Field', 'UpdateName', 'appusers.dlastchanged')
=DBSetProp('RV_USERS.dlastchanged', 'Field', 'DataType', "D")

* Props for the RV_USERS.ladministrator field.
=DBSetProp('RV_USERS.ladministrator', 'Field', 'KeyField', .F.)
=DBSetProp('RV_USERS.ladministrator', 'Field', 'Updatable', .T.)
=DBSetProp('RV_USERS.ladministrator', 'Field', 'UpdateName', 'appusers.ladministrator')
=DBSetProp('RV_USERS.ladministrator', 'Field', 'DataType', "L")

* Props for the RV_USERS.cgroup_id field.
=DBSetProp('RV_USERS.cgroup_id', 'Field', 'KeyField', .F.)
=DBSetProp('RV_USERS.cgroup_id', 'Field', 'Updatable', .T.)
=DBSetProp('RV_USERS.cgroup_id', 'Field', 'UpdateName', 'appusers.cgroup_id')
=DBSetProp('RV_USERS.cgroup_id', 'Field', 'DataType', "C(16) NOCPTRANS")

* Props for the RV_USERS.moldpasswords field.
=DBSetProp('RV_USERS.moldpasswords', 'Field', 'KeyField', .F.)
=DBSetProp('RV_USERS.moldpasswords', 'Field', 'Updatable', .T.)
=DBSetProp('RV_USERS.moldpasswords', 'Field', 'UpdateName', 'appusers.moldpasswords')
=DBSetProp('RV_USERS.moldpasswords', 'Field', 'DataType', "M")

* Props for the RV_USERS.linactive field.
=DBSetProp('RV_USERS.linactive', 'Field', 'KeyField', .F.)
=DBSetProp('RV_USERS.linactive', 'Field', 'Updatable', .T.)
=DBSetProp('RV_USERS.linactive', 'Field', 'UpdateName', 'appusers.linactive')
=DBSetProp('RV_USERS.linactive', 'Field', 'DataType', "L")
 

**************************************************
** View setup for RV_RIGHTSTONAME
**************************************************
Local vp_cGroup_id,vp_cName

vp_cGroup_id = "A"
vp_cName = "A"

Create SQL VIEW "RV_RIGHTSTONAME" REMOTE CONNECTION x_CONNECTION ;
AS SELECT * FROM apprites WHERE apprites.cgroup_id = ?vp_cGroup_id AND UPPER(apprites.cname) = UPPER(?vp_cName)

=DBSetProp('RV_RIGHTSTONAME', 'View', 'UpdateType', 1)
=DBSetProp('RV_RIGHTSTONAME', 'View', 'WhereType', 3)
=DBSetProp('RV_RIGHTSTONAME', 'View', 'FetchMemo', .T.)
=DBSetProp('RV_RIGHTSTONAME', 'View', 'SendUpdates', .F.)
=DBSetProp('RV_RIGHTSTONAME', 'View', 'UseMemoSize', 255)
=DBSetProp('RV_RIGHTSTONAME', 'View', 'FetchSize', 100)
=DBSetProp('RV_RIGHTSTONAME', 'View', 'MaxRecords', -1)
=DBSetProp('RV_RIGHTSTONAME', 'View', 'Tables', '')
=DBSetProp('RV_RIGHTSTONAME', 'View', 'FetchSize', 100)
=DBSetProp('RV_RIGHTSTONAME', 'View', 'ParameterList', "vp_cGroup_id,'C';vp_cName,'C'")
=DBSetProp('RV_RIGHTSTONAME', 'View', 'Comment', "")
=DBSetProp('RV_RIGHTSTONAME', 'View', 'BatchUpdateCount', 1)
=DBSetProp('RV_RIGHTSTONAME', 'View', 'ShareConnection', .T.)
=DBSetProp('RV_RIGHTSTONAME', 'View', 'Prepared', .F.)
=DBSetProp('RV_RIGHTSTONAME', 'View', 'CompareMemo', .T.)
=DBSetProp('RV_RIGHTSTONAME', 'View', 'FetchAsNeeded', .F.)

*!* Field Level Properties for RV_RIGHTSTONAME

* Props for the RV_RIGHTSTONAME.cgroup_id field.
=DBSetProp('RV_RIGHTSTONAME.cgroup_id', 'Field', 'KeyField', .T.)
=DBSetProp('RV_RIGHTSTONAME.cgroup_id', 'Field', 'Updatable', .F.)
=DBSetProp('RV_RIGHTSTONAME.cgroup_id', 'Field', 'UpdateName', 'apprites.cgroup_id')
=DBSetProp('RV_RIGHTSTONAME.cgroup_id', 'Field', 'DataType', "C(16) NOCPTRANS")

* Props for the RV_RIGHTSTONAME.cname field.
=DBSetProp('RV_RIGHTSTONAME.cname', 'Field', 'KeyField', .T.)
=DBSetProp('RV_RIGHTSTONAME.cname', 'Field', 'Updatable', .F.)
=DBSetProp('RV_RIGHTSTONAME.cname', 'Field', 'UpdateName', 'apprites.cname')
=DBSetProp('RV_RIGHTSTONAME.cname', 'Field', 'DataType', "C(40)")

* Props for the RV_RIGHTSTONAME.nrights field.
=DBSetProp('RV_RIGHTSTONAME.nrights', 'Field', 'KeyField', .F.)
=DBSetProp('RV_RIGHTSTONAME.nrights', 'Field', 'Updatable', .F.)
=DBSetProp('RV_RIGHTSTONAME.nrights', 'Field', 'UpdateName', 'apprites.nrights')
=DBSetProp('RV_RIGHTSTONAME.nrights', 'Field', 'DataType', "N(1)")
 

**************************************************
** View setup for RV_GROUPRIGHTS
**************************************************
Local vp_cGroup_Id

vp_cGroup_Id = "A"

Create SQL VIEW "RV_GROUPRIGHTS" REMOTE CONNECTION x_CONNECTION ;
AS SELECT * FROM apprites WHERE apprites.cgroup_id = ?vp_cGroup_Id

=DBSetProp('RV_GROUPRIGHTS', 'View', 'UpdateType', 1)
=DBSetProp('RV_GROUPRIGHTS', 'View', 'WhereType', 3)
=DBSetProp('RV_GROUPRIGHTS', 'View', 'FetchMemo', .T.)
=DBSetProp('RV_GROUPRIGHTS', 'View', 'SendUpdates', .T.)
=DBSetProp('RV_GROUPRIGHTS', 'View', 'UseMemoSize', 255)
=DBSetProp('RV_GROUPRIGHTS', 'View', 'FetchSize', 100)
=DBSetProp('RV_GROUPRIGHTS', 'View', 'MaxRecords', -1)
=DBSetProp('RV_GROUPRIGHTS', 'View', 'Tables', 'apprites')
=DBSetProp('RV_GROUPRIGHTS', 'View', 'FetchSize', 100)
=DBSetProp('RV_GROUPRIGHTS', 'View', 'ParameterList', "vp_cGroup_Id,'C'")
=DBSetProp('RV_GROUPRIGHTS', 'View', 'Comment', "")
=DBSetProp('RV_GROUPRIGHTS', 'View', 'BatchUpdateCount', 1)
=DBSetProp('RV_GROUPRIGHTS', 'View', 'ShareConnection', .T.)
=DBSetProp('RV_GROUPRIGHTS', 'View', 'Prepared', .F.)
=DBSetProp('RV_GROUPRIGHTS', 'View', 'CompareMemo', .T.)
=DBSetProp('RV_GROUPRIGHTS', 'View', 'FetchAsNeeded', .F.)

*!* Field Level Properties for RV_GROUPRIGHTS

* Props for the RV_GROUPRIGHTS.cgroup_id field.
=DBSetProp('RV_GROUPRIGHTS.cgroup_id', 'Field', 'KeyField', .T.)
=DBSetProp('RV_GROUPRIGHTS.cgroup_id', 'Field', 'Updatable', .T.)
=DBSetProp('RV_GROUPRIGHTS.cgroup_id', 'Field', 'UpdateName', 'apprites.cgroup_id')
=DBSetProp('RV_GROUPRIGHTS.cgroup_id', 'Field', 'DataType', "C(16) NOCPTRANS")

* Props for the RV_GROUPRIGHTS.cname field.
=DBSetProp('RV_GROUPRIGHTS.cname', 'Field', 'KeyField', .T.)
=DBSetProp('RV_GROUPRIGHTS.cname', 'Field', 'Updatable', .T.)
=DBSetProp('RV_GROUPRIGHTS.cname', 'Field', 'UpdateName', 'apprites.cname')
=DBSetProp('RV_GROUPRIGHTS.cname', 'Field', 'DataType', "C(40)")

* Props for the RV_GROUPRIGHTS.nrights field.
=DBSetProp('RV_GROUPRIGHTS.nrights', 'Field', 'KeyField', .F.)
=DBSetProp('RV_GROUPRIGHTS.nrights', 'Field', 'Updatable', .T.)
=DBSetProp('RV_GROUPRIGHTS.nrights', 'Field', 'UpdateName', 'apprites.nrights')
=DBSetProp('RV_GROUPRIGHTS.nrights', 'Field', 'DataType', "N(1)")


**************************************************
** View setup for RV_CURRENTLOGINS
**************************************************
Local vp_cUserId

vp_cUserId = "A"

Create SQL VIEW "RV_CURRENTLOGINS" REMOTE CONNECTION x_CONNECTION ;
AS SELECT * FROM applogin WHERE applogin.cuserid = ?vp_cUserId AND applogin.tloggedout IS NULL AND applogin.tcleared IS NULL ORDER BY applogin.tloggedin DESC

=DBSetProp('RV_CURRENTLOGINS', 'View', 'UpdateType', 1)
=DBSetProp('RV_CURRENTLOGINS', 'View', 'WhereType', 3)
=DBSetProp('RV_CURRENTLOGINS', 'View', 'FetchMemo', .T.)
=DBSetProp('RV_CURRENTLOGINS', 'View', 'SendUpdates', .T.)
=DBSetProp('RV_CURRENTLOGINS', 'View', 'UseMemoSize', 255)
=DBSetProp('RV_CURRENTLOGINS', 'View', 'FetchSize', 100)
=DBSetProp('RV_CURRENTLOGINS', 'View', 'MaxRecords', -1)
=DBSetProp('RV_CURRENTLOGINS', 'View', 'Tables', 'applogin')
=DBSetProp('RV_CURRENTLOGINS', 'View', 'FetchSize', 100)
=DBSetProp('RV_CURRENTLOGINS', 'View', 'ParameterList', "vp_cUserId,'C'")
=DBSetProp('RV_CURRENTLOGINS', 'View', 'Comment', "")
=DBSetProp('RV_CURRENTLOGINS', 'View', 'BatchUpdateCount', 1)
=DBSetProp('RV_CURRENTLOGINS', 'View', 'ShareConnection', .T.)
=DBSetProp('RV_CURRENTLOGINS', 'View', 'Prepared', .F.)
=DBSetProp('RV_CURRENTLOGINS', 'View', 'CompareMemo', .T.)
=DBSetProp('RV_CURRENTLOGINS', 'View', 'FetchAsNeeded', .F.)

*!* Field Level Properties for RV_CURRENTLOGINS

* Props for the RV_CURRENTLOGINS.cuserid field.
=DBSetProp('RV_CURRENTLOGINS.cuserid', 'Field', 'KeyField', .T.)
=DBSetProp('RV_CURRENTLOGINS.cuserid', 'Field', 'Updatable', .F.)
=DBSetProp('RV_CURRENTLOGINS.cuserid', 'Field', 'UpdateName', 'applogin.cuserid')
=DBSetProp('RV_CURRENTLOGINS.cuserid', 'Field', 'DataType', "C(30)")

* Props for the RV_CURRENTLOGINS.tloggedin field.
=DBSetProp('RV_CURRENTLOGINS.tloggedin', 'Field', 'KeyField', .T.)
=DBSetProp('RV_CURRENTLOGINS.tloggedin', 'Field', 'Updatable', .F.)
=DBSetProp('RV_CURRENTLOGINS.tloggedin', 'Field', 'UpdateName', 'applogin.tloggedin')
=DBSetProp('RV_CURRENTLOGINS.tloggedin', 'Field', 'DataType', "T")

* Props for the RV_CURRENTLOGINS.tloggedout field.
=DBSetProp('RV_CURRENTLOGINS.tloggedout', 'Field', 'KeyField', .F.)
=DBSetProp('RV_CURRENTLOGINS.tloggedout', 'Field', 'Updatable', .T.)
=DBSetProp('RV_CURRENTLOGINS.tloggedout', 'Field', 'UpdateName', 'applogin.tloggedout')
=DBSetProp('RV_CURRENTLOGINS.tloggedout', 'Field', 'DataType', "T")

* Props for the RV_CURRENTLOGINS.tcleared field.
=DBSetProp('RV_CURRENTLOGINS.tcleared', 'Field', 'KeyField', .F.)
=DBSetProp('RV_CURRENTLOGINS.tcleared', 'Field', 'Updatable', .T.)
=DBSetProp('RV_CURRENTLOGINS.tcleared', 'Field', 'UpdateName', 'applogin.tcleared')
=DBSetProp('RV_CURRENTLOGINS.tcleared', 'Field', 'DataType', "T")

* Props for the RV_CURRENTLOGINS.cclearedby field.
=DBSetProp('RV_CURRENTLOGINS.cclearedby', 'Field', 'KeyField', .F.)
=DBSetProp('RV_CURRENTLOGINS.cclearedby', 'Field', 'Updatable', .T.)
=DBSetProp('RV_CURRENTLOGINS.cclearedby', 'Field', 'UpdateName', 'applogin.cclearedby')
=DBSetProp('RV_CURRENTLOGINS.cclearedby', 'Field', 'DataType', "C(30)")